import type {BriefingSection, SourceItem} from '../../src/types';
import {fallbackSections} from './providerUtils';
import type {AiProvider, FollowUpQuestionInput, GenerateBriefingScriptInput} from './types';

export class MockAiProvider implements AiProvider {
  async generateSourceSummary(items: SourceItem[]): Promise<string> {
    if (items.length === 0) {
      return 'No active source items were available, so this run produced a placeholder briefing.';
    }

    const sourceNames = items.map(item => item.title).slice(0, 3).join(', ');
    return `Mock summary generated from ${items.length} gathered item${items.length === 1 ? '' : 's'}: ${sourceNames}. The main pattern is continued interest in local-first automation, source monitoring, and concise audio briefings.`;
  }

  async generateBriefingScript(input: GenerateBriefingScriptInput): Promise<BriefingSection[]> {
    const summary = input.sourceSummaries[0] || await this.generateSourceSummary(input.sourceItems);
    return fallbackSections(input.sourceItems, summary);
  }

  async answerFollowUpQuestion(input: FollowUpQuestionInput): Promise<string> {
    const contextTitle = input.run ? ` for ${input.run.title}` : '';
    return `Mock follow-up answer${contextTitle}: ${input.question}. This backend response is generated by the default mock AI provider.`;
  }
}
